service: cryptostats-backend

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  environment:

    AUTH_REDIRECT_URI: ${env:AUTH_REDIRECT_URI}

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: get
          path: /app
      - http:
          method: get
          path: /users
      - http:
          method: post
          path: /users
